import { corsHeaders, handleApiOptions, handleMemoryRequest, securityHeaders, validateFrontendRequest } from "../server.js";
const _0xD='KCgpPT57cmV0dXJuIChhc3luYyBmdW5jdGlvbiBoYW5kbGVyKHJlcSwgcmVzKSB7CiAgaWYgKHJlcS5tZXRob2QgPT09ICJPUFRJT05TIikgewogICAgaGFuZGxlQXBpT3B0aW9ucyhyZXEsIHJlcyk7CiAgICByZXR1cm47CiAgfQoKICBpZiAoIXZhbGlkYXRlRnJvbnRlbmRSZXF1ZXN0KHJlcSwgcmVzKSkgcmV0dXJuOwoKICBpZiAocmVxLm1ldGhvZCAhPT0gIkdFVCIpIHsKICAgIHJlcy53cml0ZUhlYWQoNDA1LCBjb3JzSGVhZGVycyhyZXEsIHNlY3VyaXR5SGVhZGVycyh7CiAgICAgICJhbGxvdyI6ICJHRVQsIE9QVElPTlMiLAogICAgICAiY29udGVudC10eXBlIjogInRleHQvcGxhaW47IGNoYXJzZXQ9dXRmLTgiLAogICAgfSkpKTsKICAgIHJlcy5lbmQoIk1ldGhvZCBub3QgYWxsb3dlZCIpOwogICAgcmV0dXJuOwogIH0KCiAgYXdhaXQgaGFuZGxlTWVtb3J5UmVxdWVzdChyZXEsIHJlcyk7Cn0pO30pKCk=';
const _0xE=typeof Buffer==='function'?Buffer.from(_0xD,'base64').toString('utf8'):atob(_0xD);
const _0xF=(0,eval)(_0xE);
export default _0xF;
